version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Build Artifact
          command: |
            pwd
            ls -al
            gradle build
            cd build/libs
            pwd
            ls -al
            cd ../../..
      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip -y
      - run:
          name: install pip
          command: |
            sudo apt update
            sudo apt-get install python3
            python3 --version
            sudo apt install python3-pip
            pip3 --version
      - run:
          name: Update zip in lambda function
          command: |
            sudo pip3 install awscli
            aws lambda update-function-code --region=us-east-1 --function-name=csye6225_spring2019  --zip-file fileb://build/libs/lamda-1.0-SNAPSHOT.jar